query listLibraries {
    library(size: 3) {
        id
        address
        books {
            id
            title
            author {
                id
                name
            }
        }
    }
    fractal {
        level
        fractal {
            level
            fractal {
                level
                fractal {
                    level
                }
            }
        }
    }
}
