package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/KenxinKun/gqlgenplayground/graph/model"
)

// Author is the resolver for the author field.
func (r *bookResolver) Author(ctx context.Context, obj *model.Book) (*model.Author, error) {
	return &model.Author{
		ID:   obj.Author.ID,
		Name: fmt.Sprint("author-of-", obj.ID),
	}, nil
}

// Fractal is the resolver for the fractal field.
func (r *fractalResolver) Fractal(ctx context.Context, obj *model.Fractal) (*model.Fractal, error) {
	return &model.Fractal{
		Level: obj.Level + 1,
	}, nil
}

// Books is the resolver for the books field.
func (r *libraryResolver) Books(ctx context.Context, obj *model.Library) ([]*model.Book, error) {
	for i, book := range obj.Books {
		book.Title = fmt.Sprint("title-", book.ID)
		book.Author = &model.Author{
			ID: fmt.Sprint("author-", i),
		}
	}
	return obj.Books, nil
}

// Library is the resolver for the library field.
func (r *queryResolver) Library(ctx context.Context, size int) (*model.Library, error) {
	books := make([]*model.Book, size)
	for i := range books {
		books[i] = &model.Book{
			ID: fmt.Sprint("book-", i),
		}
	}
	return &model.Library{
		ID:      "lib-id",
		Address: "lib address",
		Books:   books,
	}, nil
}

// Fractal is the resolver for the fractal field.
func (r *queryResolver) Fractal(ctx context.Context) (*model.Fractal, error) {
	return &model.Fractal{
		Level: 0,
	}, nil
}

// Book returns BookResolver implementation.
func (r *Resolver) Book() BookResolver { return &bookResolver{r} }

// Fractal returns FractalResolver implementation.
func (r *Resolver) Fractal() FractalResolver { return &fractalResolver{r} }

// Library returns LibraryResolver implementation.
func (r *Resolver) Library() LibraryResolver { return &libraryResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type bookResolver struct{ *Resolver }
type fractalResolver struct{ *Resolver }
type libraryResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
